apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: hello-app-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-KSBM-C37J2R
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.1.0-r3
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/hello-app-rest:35ae24badbde71b9b5ca0f42b700e25adb7bbd47
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
